apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: depl2
  template:
    metadata:
      labels:
        app: depl2
    spec:
      containers:
      - name: depl2
        image: bstashchuk/k8s-web-hello
        resources:
          limits:
            cpu: 2000m
            memory: 2000Mi
          requests:
            cpu: 250m
            memory: 250Mi
        ports:
        - containerPort: 3000
      tolerations:
      - key: "nodeGroup"
        value: "shared"
        effect: "NoSchedule"
      - key: "nodeGroup"
        value: "2excl"
        effect: "NoSchedule"