apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 2
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: talhawaheed/webapp:4
          resources:
            limits:
              cpu: 2000m
              memory: 2000Mi
            requests:
              cpu: 250m
              memory: 250Mi
          ports:
            - containerPort: 3000
              protocol: TCP
      tolerations:
      - key: "nodeGroup"
        value: "shared"
        effect: "NoSchedule"
      - key: "nodeGroup"
        value: "excl1"
        effect: "NoSchedule"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  selector:
    matchLabels:
      app: app2
  replicas: 2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image: talhawaheed/webapp:4
          resources:
            limits:
              cpu: 2000m
              memory: 2000Mi
            requests:
              cpu: 250m
              memory: 250Mi
          ports:
            - containerPort: 3000
              protocol: TCP
      tolerations:
      - key: "nodeGroup"
        value: "shared"
        effect: "NoSchedule"
      - key: "nodeGroup"
        value: "excl2"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  type: NodePort
  selector:
    app: app1
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  type: NodePort
  selector:
    app: app2
  ports:
  - port: 3000
    targetPort: 3000