apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw1
spec:
  selector:
    matchLabels:
      run: hw1
  replicas: 2
  template:
    metadata:
      labels:
        run: hw1
    spec:
      containers:
        - name: hw1
          image: bstashchuk/k8s-web-hello:2.0.0
          resources:
            limits:
              cpu: 2000m
              memory: 2000Mi
            requests:
              cpu: 250m
              memory: 250Mi
          ports:
            - containerPort: 3000
              protocol: TCP
      tolerations:
      - key: "nodeGroup"
        value: "shared"
        effect: "NoSchedule"
      - key: "nodeGroup"
        value: "excl1"
        effect: "NoSchedule"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw2
spec:
  selector:
    matchLabels:
      run: hw2
  replicas: 2
  template:
    metadata:
      labels:
        run: hw2
    spec:
      containers:
        - name: hw2
          image: bstashchuk/k8s-web-hello:2.0.0
          resources:
            limits:
              cpu: 2000m
              memory: 2000Mi
            requests:
              cpu: 250m
              memory: 250Mi
          ports:
            - containerPort: 3000
              protocol: TCP
      tolerations:
      - key: "nodeGroup"
        value: "shared"
        effect: "NoSchedule"
      - key: "nodeGroup"
        value: "excl2"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: hw1
spec:
  type: NodePort
  selector:
    run: hw1
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hw2
spec:
  type: NodePort
  selector:
    run: hw2
  ports:
  - port: 3000
    targetPort: 3000