apiVersion: v1
kind: Pod
metadata:
  name: app1
  labels:
    app: app1
spec:
  containers:
    - name: app1
      image: talhawaheed/webapp:4
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 2000m
          memory: 2000Mi
        requests:
          cpu: 500m
          memory: 500Mi
      ports:
        - containerPort: 3000
          protocol: TCP
  restartPolicy: Never
  tolerations:
  - key: "nodeGroup"
    value: "excl1"
    effect: "NoSchedule"