apiVersion: v1
kind: Service
metadata:
  name: envoy-lb-app1
  labels:
    app: envoy-lb-app1
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: envoy-lb-app1