apiVersion: v1
kind: Service
metadata:
  name: hw1
spec:
  type: LoadBalancer
  selector:
    run: hw1
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hw2
spec:
  type: LoadBalancer
  selector:
    run: hw2
  ports:
  - port: 8080
    targetPort: 8080